export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  LOGOUT_ALL: "LOGOUT_ALL",
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  PASSWORD_RESET: "PASSWORD_RESET",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ROLE_CHANGED: "ROLE_CHANGED",
  ACCOUNT_UNLOCKED: "ACCOUNT_UNLOCKED",
  ACCOUNT_SELF_DISABLED: "ACCOUNT_SELF_DISABLED",
  TWO_FA_LOGIN_SUCCESS: "2FA_LOGIN_SUCCESS",
  USER_DELETED_PERMANENTLY: "USER_DELETED_PERMANENTLY",
  PASSWORD_UPDATED_LOGGED_IN: "PASSWORD_UPDATED_LOGGED_IN",
  SOCIAL_LINKS_UPDATE: "SOCIAL_LINKS_UPDATE",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  TWO_FA_ENABLED_SUCCESSFULLY: "2FA_ENABLED_SUCCESSFULLY",
  EMAIL_CHANGED: "EMAIL_CHANGED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_ENABLED: "ACCOUNT_ENABLED",
  TWO_FA_ENABLED: "2FA_ENABLED",
  TWO_FA_DISABLED: "2FA_DISABLED",
  TWO_FA_LOGIN_SUCCESS:"TWO_FA_LOGIN_SUCCESS"
};

export const AUDIT_STATUS = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
};