apiVersion: argoproj.io/v1alpha1 
kind: Rollout                 
metadata:
  name: gateway-service
  namespace: xynapse-stage
spec:
  replicas: 2                   
  selector:
    matchLabels:
      app: gateway
  strategy:
    canary:
      steps:
        - setWeight: 10       
        - pause: {duration: 2m} 
        - setWeight: 40       
        - pause: {duration: 1m}
        - setWeight: 100     
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        # --- VAULT CONFIG ---
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "xynapse-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/xynapse/global"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/xynapse/global" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end -}}
    spec:
      containers:
      - name: gateway
        image: us-central1-docker.pkg.dev/project-5e783ec5-d363-4cc7-884/xynapse-mono-repo/gateway:v1.0.1
        command: ["/bin/sh", "-c"]
        args:
          - |
            # 1. Wait for vault file to exist
            while [ ! -f /vault/secrets/config ]; do echo "Waiting for gateway secrets..."; sleep 1; done;
            # 2. Source the secrets as real environment variables
            source /vault/secrets/config
            # 3. Start the gateway service
            node apps/gateway-service/src/index.js
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: xynapse-stage
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000