apiVersion: argoproj.io/v1alpha1 
kind: Rollout              
metadata:
  name: course-service
  namespace: xynapse-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course
  strategy:
    canary:
      steps:
        - setWeight: 20       
        - pause: {duration: 2m} 
        - setWeight: 50      
        - pause: {duration: 1m}
        - setWeight: 100     
  template:
    metadata:
      labels:
        app: course
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "xynapse-role" 
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/xynapse/global"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/xynapse/global" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end -}}
    spec:
      containers:
      - name: course
        image: us-central1-docker.pkg.dev/project-5e783ec5-d363-4cc7-884/xynapse-mono-repo/course:v1.0.1
        command: ["/bin/sh", "-c"]
        args:
          - |
            # 1. Jab tak Vault file render na kar de, wait karo (Race Condition Fix)
            while [ ! -f /vault/secrets/config ]; do echo "Waiting for secrets..."; sleep 1; done;
            
            # 2. File ko source karo taaki 'export' commands execute ho jayein
            source /vault/secrets/config
            
            # 3. Ab apni application start karo
            node apps/course-service/src/index.js 
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: xynapse-stage
spec:
  selector:
    app: course
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002