apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcq-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0rishav/xynapse-mono-repo.git 
    targetRevision: stage  
    path: k8s-manifests/mcq 
  destination:
    server: https://kubernetes.default.svc
    namespace: xynapse-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 