apiVersion: argoproj.io/v1alpha1 
kind: Rollout                
metadata:
  name: mcq-service
  namespace: xynapse-stage
spec:
  replicas: 2                 
  selector:
    matchLabels:
      app: mcq
  # --- CANARY STRATEGY ---
  strategy:
    canary:
      steps:
        - setWeight: 20       
        - pause: {duration: 1m} 
        - setWeight: 60      
        - pause: {duration: 1m}
        - setWeight: 100      
  # -----------------------
  template:
    metadata:
      labels:
        app: mcq
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "xynapse-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/xynapse/mcq"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/xynapse/mcq" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end -}}
    spec:
      containers:
      - name: mcq
        image: gcr.io/project-5e783ec5-d363-4cc7-884/mcq:v1.0.1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: mcq-service
  namespace: xynapse-stage
spec:
  selector:
    app: mcq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082