apiVersion: argoproj.io/v1alpha1 
kind: Rollout                 
metadata:
  name: mcq-service
  namespace: xynapse-stage
spec:
  replicas: 2                   
  selector:
    matchLabels:
      app: mcq
  strategy:
    canary:
      steps:
        - setWeight: 20       
        - pause: {duration: 1m} 
        - setWeight: 60      
        - pause: {duration: 1m}
        - setWeight: 100      
  template:
    metadata:
      labels:
        app: mcq
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "xynapse-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/xynapse/global"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/xynapse/global" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end -}}
    spec:
      containers:
      - name: mcq
        image: us-central1-docker.pkg.dev/project-5e783ec5-d363-4cc7-884/xynapse-mono-repo/mcq:v1.0.1
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Vault file render hone ka wait karo
            while [ ! -f /vault/secrets/config ]; do echo "Waiting for MCQ secrets..."; sleep 1; done;
            
            # Environment variables load karo
            source /vault/secrets/config
            
            # Application start karo
            node apps/mcq-service/src/index.js
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: mcq-service
  namespace: xynapse-stage
spec:
  selector:
    app: mcq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082