name: "Stage 1: Build & Integrity"

on:
  pull_request:
    branches: [main, release, stage]
    paths:
      - 'apps/**'
      - 'packages/common/**'
  
  push:
    branches: [main, release, stage]
    paths:
      - 'apps/**'
      - 'packages/common/**'

jobs:
  # DECISION MAKER
  detect-changes:
    runs-on: [self-hosted] 
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            identity: ['apps/identity-service/**', 'packages/common/**']
            course: ['apps/course-service/**', 'packages/common/**']
            mcq: ['apps/mcq-service/**', 'packages/common/**']
            gateway: ['apps/gateway-service/**', 'packages/common/**']

  # CODE QUALITY
  analyze:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' }}
    runs-on: ubuntu-latest 
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript' 

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # HIGH-PERFORMANCE BUILD
  build:
    needs: [detect-changes, analyze]
    if: ${{ needs.detect-changes.outputs.services != '[]' }}
    
    runs-on: >-
      ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release') 
            && 'arc-runner-prod-fresh' || 'arc-runner-dev-fresh' }}
    
    environment: >-
      ${{ github.ref == 'refs/heads/main' && 'production' || 
          github.ref == 'refs/heads/release' && 'release' || 
          'staging' }}

    strategy:
      fail-fast: false 
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    
    permissions:
      contents: read
      id-token: write 
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Google OIDC Auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'     
          create_credentials_file: true    
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Docker Login (GCR)
        run: gcloud auth configure-docker gcr.io --quiet 

      - name: Execute Smart Build
        uses: ./.github/actions/smart-build
        with:
          service_name: ${{ matrix.service }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}